POST http://rentman.test/api/webhook/rentman HTTP/1.1
content-type: application/json
digest: sha512=8e7fafc1d9474d51561b3ebf994a860f0c81c406cdbf0c925f4e0e4e53ee1b38719dd35c0b0da672fd692981bc938842fb4efdee83e90ce9237fd7a51275f20f

{"account":"ledvisions","user":{"itemType":"Crew","id":33,"ref":"/crew/33"},"eventType":"create","itemType":"Project","items":[{"id":750,"ref":"/projects/750","parent":null}],"eventDate":"2026-02-13T17:29:43+01:00"}