POST http://rentman.test/api/webhook/rentman HTTP/1.1
content-type: application/json
digest: sha512=092df9438cc087da47b4c0366cfa225201b83ecf28bfbdd190526fe4ddc203b8f204b1dbb9e07e3ca12d6749cd11eaf713bed4d591b5f0d7ecc5a6dced8c12ff


{"account":"llstageservice","user":{"itemType":"Crew","id":33,"ref":"/crew/33"},"eventType":"update","itemType":"Project","items":[{"id":8588,"ref":"/projects/8588","parent":null}],"eventDate":"2026-02-17T22:00:11+01:00"}