POST http://rentman.test/api/webhook/rentman HTTP/1.1
content-type: application/json
digest: sha512=4f3e2eda183e05f76280a90874876574e21926b155dfcd71ee0b751d961dac80cfeb28b4743fdab142d017b31631758095204b87fb4978b4dfb79e6c7f9da2b7

{
  "account":"llstageservice",
  "user":
  {
    "itemType":"Crew",
    "id":33,
    "ref":"/crew/33"
  },
  "eventType":"update",
  "itemType":"Project",
  "items":[
    {
      "id":8468,"ref":"/projects/8468","parent":null
    }
  ],
  "eventDate":"2026-02-13T10:16:09+01:00"
}