POST http://rentman.test/api/webhook/rentman HTTP/1.1
content-type: application/json
digest: sha512=99cd7de598a53393ead1f86ec23648a39b2101c2087d7fc1d6f074c63b3b433efa70c91a5c714dad12a3ab10b3fd44a1d2956c1880e84de81a70dda7b93f5cfb

{
  "account":"llstageservice",
  "user":
  {
    "itemType":"Crew",
    "id":1121,
    "ref":"/crew/1121"},
    "eventType":"update",
    "itemType":"Project",
    "items":[
      {
        "id":8468,"ref":"/projects/8468","parent":null
      }
    ],
    "eventDate":"2026-02-13T10:16:09+01:00"
  }