POST http://rentman.test/api/webhook/rentman HTTP/1.1
content-type: application/json
digest: sha512=9cf9fc43501d6ea0c63632299578a00093ceab422ce82b27884ce754f9e8af044c0c2de7e4e5f9d894575aa6db7100815f3bfc2bbd179cbb61a5392e57d15927

{"account":"ledvisions","user":{"itemType":"Crew","id":280,"ref":"/crew/280"},"eventType":"update","itemType":"Subproject","items":[{"id":1489,"ref":"/subprojects/1489","parent":{"id":729,"itemType":"Project","ref":"/projects/729"}},{"id":1490,"ref":"/subprojects/1490","parent":{"id":729,"itemType":"Project","ref":"/projects/729"}}],"eventDate":"2026-02-14T16:56:44+01:00"}