POST http://rentman.test/api/webhook/rentman HTTP/1.1
content-type: application/json
digest: sha512=4d5d18f8901b4506a78cc8e61829fb496a42b5b5f6ba65dd9db271db7461263ca25ddbfaac69da21a5195cef360d43e703c300ed8eb0c20d26d472d930e07c98

{
  "account":"llstageservice",
  "user":
  {
    "itemType":"Crew",
    "id":33,
    "ref":"/crew/33"
  },
  "eventType":"delete",
  "itemType":"Subproject",
  "items":[11358],
  "eventDate":"2026-02-14T19:41:48+01:00"
}